image: Visual Studio 2017
skip_tags: true

install:
  - git submodule update --init --recursive

build_script:
  - scripts\build-appveyor

artifacts:
  - path: 'windows\Release'
    name: breakpad-tools-windows
    type: zip

deploy:
  provider: S3
  access_key_id: AKIAJKYWAF3QS7SFL75Q
  secret_access_key:
    secure: Jk6F78pedve8W++5KDviGUw07CA5mjtuAZNBbiY1zbAaDCtZhX0lZOVQLns36eRp
  bucket: getsentry-builds
  set_public: true
  folder: $(APPVEYOR_REPO_NAME)
  artifact: breakpad-tools-windows
